## 9주차 recsys basic 과제: Q1, Q2에있는 빈칸을 채워주세요

## Movielens data 탐방하기

In [1]:

import argparse

import torch

#다양한 hyperparameter를 조절하기 위한 argparser
argparser = argparse.ArgumentParser()
argparser.add_argument('--latent_dim', type=int, default=10)
argparser.add_argument('--batch_size', type=int, default=500)
args = argparser.parse_args("")

In [2]:
import pandas as pd
import numpy as np
# 이건 토치용입니다.
from torch.utils.data import Dataset, DataLoader
import torch

class MlDataLoader(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]


## 무비렌즈 데이터 불러주는  class: ml100k
ML100k 클래스에서 data_path만 여러분이 u.data를 불러올 수 있는 경로로 바꿔주세요!!

In [3]:
import pandas as pd
# traintest split
from sklearn.model_selection import train_test_split
import torch
from torch.utils.data import Dataset, DataLoader
#from src.preprocess.mldataloader import MlDataLoader


class ML100k():

    def __init__(self,args) -> None:
        self.args=args
        self.call_data(args)
        pass

    def call_data(self, args) -> None:
        self.args = args
        #data_path="data/ml-100k/u.data" #이부분을 다운받은 데이터를 코랩에서 실행할 수 잇도록 바꿔주세요

        self.data= pd.read_csv("u.data", sep='\t', header=None, names=['user', 'item', 'rating', 'timestamp'])
        self.num_users = self.data.user.nunique()
        self.num_items = self.data.item.nunique()
        self.num_ratings = len(self.data)

        # user, item index를 0부터 시작하도록 변경-. nn.Embedding에서 index가 0부터 시작하므로 1을 빼줍니다.
        self.data.user = self.data.user -1
        self.data.item = self.data.item -1


        self.x = self.data[['user', 'item']].values
        self.y= self.data.rating.values

        # split data into train and test
        self.x_train, self.x_test, self.y_train, self.y_test = train_test_split(self.x, self.y, test_size=0.2, random_state=42)




    def get_dataframe(self):
        # sort dataframe by user
        return self.data[['user', 'item','rating']]


    def load_torch_data(self):

        # convert x to integer, y to floattenser
        self.x_train = torch.tensor(self.x_train, dtype=torch.long)
        self.y_train = torch.tensor(self.y_train, dtype=torch.float)
        self.x_test = torch.tensor(self.x_test, dtype=torch.long)
        self.y_test = torch.tensor(self.y_test, dtype=torch.float)


        train_dataset = MlDataLoader(self.x_train, self.y_train)
        test_dataset = MlDataLoader(self.x_test, self.y_test)

        train_loader = DataLoader(train_dataset, batch_size=self.args.batch_size, shuffle=True)
        test_loader = DataLoader(test_dataset, batch_size=self.args.batch_size, shuffle=False)

        return train_loader, test_loader


In [4]:
ml100k=ML100k(args)
dataframe=ml100k.get_dataframe()

In [5]:
dataframe# 아래와 같이 user, item, rating으로 이루어진 데이터프레임이 나오게 됩니다.

user  item  rating
0       195   241       3
1       185   301       3
2        21   376       1
3       243    50       2
4       165   345       1
...     ...   ...     ...
99995   879   475       3
99996   715   203       5
99997   275  1089       1
99998    12   224       2
99999    11   202       3

[100000 rows x 3 columns]

##  Q1 : 해당 데이터 프레임을 통해서 각각의 유저가 item들의 점수를 어떻게 매겼는지를 나타내는 user-item matrix(rating matrix)를 만들어 주세요!!
이 때 유저가 시청하지 않은 데이터는 -1로 처리해주세요!

In [17]:
# 사용자별 평점 매트릭스 생성
rating_matrix = dataframe.pivot_table(index='user', columns='item', values='rating', fill_value=-1)

print(rating_matrix.head())

item  0     1     2     3     4     5     6     7     8     9     ...  1672  \
user                                                              ...         
0        5     3     4     3     3     5     4     1     5     3  ...    -1   
1        4    -1    -1    -1    -1    -1    -1    -1    -1     2  ...    -1   
2       -1    -1    -1    -1    -1    -1    -1    -1    -1    -1  ...    -1   
3       -1    -1    -1    -1    -1    -1    -1    -1    -1    -1  ...    -1   
4        4     3    -1    -1    -1    -1    -1    -1    -1    -1  ...    -1   

item  1673  1674  1675  1676  1677  1678  1679  1680  1681  
user                                                        
0       -1    -1    -1    -1    -1    -1    -1    -1    -1  
1       -1    -1    -1    -1    -1    -1    -1    -1    -1  
2       -1    -1    -1    -1    -1    -1    -1    -1    -1  
3       -1    -1    -1    -1    -1    -1    -1    -1    -1  
4       -1    -1    -1    -1    -1    -1    -1    -1    -1  

[5 rows x 1682 col

In [19]:
rating_matrix

item  0     1     2     3     4     5     6     7     8     9     ...  1672  \
user                                                              ...         
0        5     3     4     3     3     5     4     1     5     3  ...    -1   
1        4    -1    -1    -1    -1    -1    -1    -1    -1     2  ...    -1   
2       -1    -1    -1    -1    -1    -1    -1    -1    -1    -1  ...    -1   
3       -1    -1    -1    -1    -1    -1    -1    -1    -1    -1  ...    -1   
4        4     3    -1    -1    -1    -1    -1    -1    -1    -1  ...    -1   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
938     -1    -1    -1    -1    -1    -1    -1    -1     5    -1  ...    -1   
939     -1    -1    -1     2    -1    -1     4     5     3    -1  ...    -1   
940      5    -1    -1    -1    -1    -1     4    -1    -1    -1  ...    -1   
941     -1    -1    -1    -1    -1    -1    -1    -1    -1    -1  ...    -1   
942     -1     5    -1    -1    -1    -1    -1    -1     3    -1  ...    -1   

item  1673  1674  1675  1676  1677  1678  1679  1680  1681  
user                                                        
0       -1    -1    -1    -1    -1    -1    -1    -1    -1  
1       -1    -1    -1    -1    -1    -1    -1    -1    -1  
2       -1    -1    -1    -1    -1    -1    -1    -1    -1  
3       -1    -1    -1    -1    -1    -1    -1    -1    -1  
4       -1    -1    -1    -1    -1    -1    -1    -1    -1  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
938     -1    -1    -1    -1    -1    -1    -1    -1    -1  
939     -1    -1    -1    -1    -1    -1    -1    -1    -1  
940     -1    -1    -1    -1    -1    -1    -1    -1    -1  
941     -1    -1    -1    -1    -1    -1    -1    -1    -1  
942     -1    -1    -1    -1    -1    -1    -1    -1    -1  

[943 rows x 1682 columns]

## -1로 채워진 부분들을 채워주기 위해서 matrix factorization을 해봅시다
이때 torch를 활용해서 sgd기반의 방법으로 user embedding과 item embedding을 훈련시켜 보겠습니다.


In [10]:
# 위에 ml100k 클래스에서 torch dataloader를 불러오는 함수를 호출하여 데이터로더 형태의 train_loader, test_loader를 불러옵니다.
train_loader, test_loader=ml100k.load_torch_data()

이제 Matrix factorization model을 구현해봅시다.

In [11]:
import torch
import torch.nn as nn

class MF(nn.Module):

    def __init__(self, args ,num_users,num_items) -> None:
        super().__init__()
        self.num_users = num_users
        self.num_items = num_items
        self.latent_dim = args.latent_dim
        self.user_embedding = nn.Embedding(self.num_users, self.latent_dim)
        self.item_embedding = nn.Embedding(self.num_items, self.latent_dim)
        #self.dropout = nn.Dropout(p=args.dropout)


    def forward(self, x) -> None:
        # x: (batch_size, 2) : index 0:user, index 1:item
        user = x[:, 0]
        item = x[:, 1]
        user = self.user_embedding(user)
        #user shape: (batch_size, latent_dim) 우리가 원하는 유저가 표현된 latent_dim 차원의 벡터
        item = self.item_embedding(item)
        #item shape: (batch_size, latent_dim) 우리가 원하는 아이템이 표현된 latent_dim 차원의 벡터

        out = torch.sum(user * item, dim=1) # 내적을 통해서 구하기,

        return out


여기서 잠깐 EMbedding이 어떻게 동작하는지 확인한번만 해봅시다

In [12]:
uemb_temp=nn.Embedding(ml100k.num_users, args.latent_dim)
iembe_temp=nn.Embedding(ml100k.num_items, args.latent_dim)

In [13]:
print(uemb_temp.weight.shape)
print(iembe_temp.weight.shape)

torch.Size([943, 10])
torch.Size([1682, 10])


In [14]:
uemb_temp.weight

Parameter containing:
tensor([[ 0.4173, -0.8748, -0.0778,  ...,  1.3850, -1.0010, -1.3320],
        [ 1.2981, -0.5878,  1.1104,  ...,  1.0212,  1.8903,  1.1419],
        [-0.2785,  0.3792, -0.5347,  ..., -1.1077, -1.0209, -0.8598],
        ...,
        [-1.0496, -0.4530, -0.5304,  ...,  0.7687, -0.5009,  1.8942],
        [ 0.1621, -0.6542,  0.6056,  ...,  1.1723, -0.2899,  0.0853],
        [-1.0962, -0.2317, -0.0988,  ..., -0.2407,  0.9894, -1.8161]],
       requires_grad=True)

In [15]:
iembe_temp.weight

Parameter containing:
tensor([[-0.4598,  0.2386, -1.0559,  ..., -0.8190,  0.6295, -2.0794],
        [-0.0040,  0.4529,  0.0159,  ...,  0.6669,  0.3477,  0.7629],
        [ 0.5822, -1.4538, -0.7540,  ..., -0.7701, -0.9398,  0.2558],
        ...,
        [ 0.4830, -0.9298,  1.2197,  ...,  2.2011, -0.5510, -0.8702],
        [-0.3751, -0.0716, -1.4952,  ..., -1.1079,  1.0924,  1.5000],
        [-0.5143,  1.0195,  1.2380,  ...,  0.8392, -0.7415,  1.0021]],
       requires_grad=True)

즉 nn.Embedding을 통해서 유저, 아이템에 대한 embedding matrix를 저장하고 훈련시킬 수 잇는 네트워크라고 보시면 됩니다.(자연어에서 사용되는 nn.embedding과 같습니다.`)

그럼 이제 모델을 훈련시켜봅시다. 엄밀히 훈련시키려면 regularization,earlystopping등의 장치가 추가적으로 필요하지만, 돌아가는거만 확인하기 위해서 최대한 간단한 형태로 구현했습니다.

In [16]:
import torch
class Trainer():

    def __init__(self, model, optimizer, criterion, device):
        self.model = model
        self.optimizer = optimizer
        self.criterion = criterion
        self.device = device


    def train(self, data, test_data, epochs):
        for epoch in range(epochs):
            for (x,y) in data:
                x = x.to(self.device)
                y = y.to(self.device)
                self.optimizer.zero_grad()
                output = self.model(x)
                loss = self.criterion(output, y)
                loss.backward()
                self.optimizer.step()
                # print test loss
            test_loss = 0
            with torch.no_grad():
                for (x,y) in test_data:
                    x = x.to(self.device)
                    y = y.to(self.device)
                    output = self.model(x)
                    test_loss += self.criterion(output, y)

                #normalize test loss
            test_loss /= len(test_data)
            print(f"Epoch {epoch} train loss: {loss.item()} test loss: {test_loss.item()}")

        print("Training finished")

In [20]:
# model, optimizer, criterion, device를 정의합니다.
model = MF(args, ml100k.num_users, ml100k.num_items)
optimizer = torch.optim.Adam(model.parameters(),lr=0.05)
criterion = nn.MSELoss()
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)
criterion.to(device)

# trainer를 정의합니다.
trainer = Trainer(model, optimizer, criterion, device)
trainer.train(train_loader, test_loader, 10)

Epoch 0 train loss: 2.3427231311798096 test loss: 2.04331636428833
Epoch 1 train loss: 1.0835976600646973 test loss: 1.3063642978668213
Epoch 2 train loss: 0.9071478843688965 test loss: 1.2280040979385376
Epoch 3 train loss: 1.104609489440918 test loss: 1.2189949750900269
Epoch 4 train loss: 1.0121906995773315 test loss: 1.2199963331222534
Epoch 5 train loss: 0.9372559785842896 test loss: 1.2451419830322266
Epoch 6 train loss: 0.8623299598693848 test loss: 1.2632856369018555
Epoch 7 train loss: 0.8764429688453674 test loss: 1.2647650241851807
Epoch 8 train loss: 0.9082493185997009 test loss: 1.263665795326233
Epoch 9 train loss: 0.871284544467926 test loss: 1.2579360008239746
Training finished


이제 아까 빈칸이었던 user-item matrix를 채워봅시다!




In [21]:
user_item_matrix=dataframe.pivot(index='user', columns='item', values='rating').fillna(-1) #pandas로 하면 너무느려져서 numpy로 바구고 진행합시다
user_item_matrix=user_item_matrix.to_numpy()

In [22]:
model=model.cpu() #모델을 cpu로 바꿔주고
# 훈련된 embedding을 numpy로 바꿔줍니다.
np_userembedding=model.user_embedding.weight.detach().numpy()
np_itemembedding=model.item_embedding.weight.detach().numpy()

In [23]:
user_item_matrix

array([[ 5.,  3.,  4., ..., -1., -1., -1.],
       [ 4., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       ...,
       [ 5., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1.,  5., -1., ..., -1., -1., -1.]])

## Q2. 아래 코드를 완성해주세요!

In [27]:
# 아래 코드를 완성해주세요
for i in range(ml100k.num_users):
    for j in range(ml100k.num_items):
        if user_item_matrix[i,j]==-1:
            user_item_matrix[i,j]=np.dot(np_userembedding[i], np_itemembedding[j].T) # 물음표를 채워주세요! , HInt  : 내적

## 결과

In [28]:
user_item_matrix

array([[ 5.        ,  3.        ,  4.        , ..., -1.54693031,
         3.51180267,  2.02942824],
       [ 4.        ,  3.49032474,  2.99404049, ..., -0.29767695,
         4.70736408,  0.96623838],
       [ 1.93448639,  1.72423315,  2.97911596, ..., -0.46843758,
         2.19655418,  2.85777092],
       ...,
       [ 5.        ,  3.54381466,  5.48323059, ..., -0.41113791,
         2.92187405,  1.06674337],
       [ 4.32546425,  4.00282669,  4.47779512, ...,  1.46448803,
         4.8855052 ,  0.77987713],
       [ 3.84353924,  5.        ,  2.77055311, ...,  1.02700281,
         3.10824585,  2.73257947]])

### 추가로....
결과를 보면 범위가 -3 에서  +5보다 큰 값도 나왔는데, 일반적으로는 0.5~5 사이로 normalization을 시켜주는 것 같습니다. 이건 생략하겠습니다 ㅎㅎ..